name: Java CI/CD with Maven

on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        java-package: 'jdk+fx'
        cache: maven
    - name: Build and run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn -B package --file pom.xml

    - name: Upload resulting executable
      uses: actions/upload-artifact@v2
      with:
        name: jar file
        path: target/sae201-1.0-SNAPSHOT.jar
